export const productsInfo = [
  {
    id: 1,
    img: "./images/products/product-home-1.png",
    title: "Pueraria Mirifica And Study Phyto Estrogens",
    price: "599",
    isNew: true,
    country: "en-US",
    currency: "USD",
  },
  {
    id: 2,
    img: "./images/products/product-home-2.png",
    title: "Pueraria Mirifica And Study Phyto Estrogens",
    price: "599",
    isNew: true,
    country: "en-US",
    currency: "USD",
  },
  {
    id: 3,
    img: "./images/products/product-home-3.png",
    title: "Pueraria Mirifica And Study Phyto Estrogens",
    price: "599",
    isNew: true,
    country: "en-US",
    currency: "USD",
  },
  {
    id: 4,
    img: "./images/products/product-home-4.png",
    title: "Pueraria Mirifica And Study Phyto Estrogens",
    price: "599",
    isNew: false,
    country: "en-US",
    currency: "USD",
  },
  {
    id: 5,
    img: "./images/products/product-home-5.png",
    title: "Pueraria Mirifica And Study Phyto Estrogens",
    price: "599",
    isNew: true,
    country: "en-US",
    currency: "USD",
  },
  {
    id: 6,
    img: "./images/products/product-home-6.png",
    title: "Pueraria Mirifica And Study Phyto Estrogens",
    price: "599",
    isNew: false,
    country: "en-US",
    currency: "USD",
  },
  {
    id: 7,
    img: "./images/products/product-home-7.png",
    title: "Pueraria Mirifica And Study Phyto Estrogens",
    price: "599",
    isNew: true,
    country: "en-US",
    currency: "USD",
  },
  {
    id: 8,
    img: "./images/products/product-home-8.png",
    title: "Pueraria Mirifica And Study Phyto Estrogens",
    price: "599",
    isNew: false,
    country: "en-US",
    currency: "USD",
  },
];
